drop table if exists permissao cascade;
drop table if exists usuario cascade;
drop table if exists quest_atributo cascade;
drop table if exists quest_item cascade;
drop table if exists personagem_item cascade;
drop table if exists personagem_atributo cascade;
drop table if exists classe_atributo cascade;
drop table if exists atributo cascade;
drop table if exists quest cascade;
drop table if exists personagem cascade;
drop table if exists classe cascade;
drop table if exists item cascade;
drop type if exists cla;
drop type if exists item_tipos;
drop type if exists atributos;


create type cla as enum ('HIGIENIZADORES', 'ESTUDIOSOS');
create type item_tipos as enum ('VIDA', 'FORCA', 'NIVEL', 'AGILIDADE', 'DESTREZA', 'ARMA', 'ARMADURA');
create type atributos as enum ('VIDA', 'FORCA', 'NIVEL', 'DESTREZA', 'AGILIDADE', 'FAMA');

create table usuario (
	id bigint generated by default as identity not null,
	nome varchar(100) not null,
	senha varchar(100) not null,
	ativo BOOLEAN not null
);
alter table usuario add constraint pk_usuario primary key (id);
alter table usuario add constraint uk_usuario_nome unique (nome);


create table permissao (
	id bigint generated by default as identity not null,
	nome varchar(100) not null,
	usuario_id BIGINT not null
);
alter table permissao add constraint pk_permissao primary key (id);
alter table permissao add constraint uk_permissao unique (nome, usuario_id);
alter table permissao add constraint fk_permissao_usuario foreign key (usuario_id) references usuario;

create table atributo (
    id bigint generated by default as identity not null,
    atributo atributos not null,
    valor numeric default 0.0
);
alter table atributo add constraint pk_atributo primary key (id);

create table classe (
    id bigint generated by default as identity not null,
    nome varchar(100) not null,
    imagem text not null,
    cla cla not null,
    descricao text not null
);
alter table classe add constraint pk_classe primary key (id);

create table classe_atributo (
    id_classe bigint not null,
    id_atributo bigint not null
);
alter table classe_atributo add constraint fk_classe_atributo_id_classe foreign key (id_classe) references classe;
alter table classe_atributo add constraint fk_classe_atributo_id_atributo foreign key (id_atributo) references atributo;


create table quest (
    id bigint generated by default as identity not null,
    tempo int not null,
    imagem text not null,
    descricao text not null
);
alter table quest add constraint pk_quest primary key (id);


create table quest_atributo (
    id_quest bigint not null,
    id_atributo bigint not null
);

alter table quest_atributo add constraint fk_quest_atributo_id_quest foreign key (id_quest) references quest;
alter table quest_atributo add constraint fk_quest_atributo_id_atributo foreign key (id_atributo) references atributo;

create table personagem (
    id bigint generated by default as identity not null,
    nome varchar(100) not null,
    id_quest bigint,
    dinheiro numeric not null,
    id_classe bigint not null,
    termino_ultima_quest timestamp,
    vitorias int default 0,
    derrotas int default 0,
    id_usuario bigint not null
);
alter table personagem add constraint pk_personagem primary key (id);
alter table personagem add constraint fk_personagem_id_classe foreign key (id_classe) references classe;
alter table personagem add constraint fk_personagem_id_quest foreign key (id_quest) references quest;
alter table personagem add constraint fk_personagem_id_usuario foreign key (id_usuario) references usuario;

create table personagem_atributo (
    id_personagem bigint not null,
    id_atributo bigint not null
);
alter table personagem_atributo add constraint fk_personagem_atributo_id_personagem foreign key (id_personagem) references personagem;
alter table personagem_atributo add constraint fk_personagem_atributo_id_atributo foreign key (id_atributo) references atributo;

create table item (
    id bigint generated by default as identity not null,
    cla cla,
    imagem text not null,
    preco numeric not null,
    nome varchar(100) not null,
    tipo item_tipos not null,
    valor numeric not null,
    descricao text not null
);
alter table item add constraint pk_item primary key (id);

create table personagem_item (
    id_personagem bigint not null,
    id_item bigint not null
);
alter table personagem_item add constraint fk_usuario_item_id_personagem foreign key (id_personagem) references personagem;
alter table personagem_item add constraint fk_usuario_item_id_item foreign key (id_item) references item;


create table quest_item (
    id_quest bigint not null,
    id_item bigint not null
);
alter table quest_item add constraint fk_quest_item_id_quest foreign key (id_quest) references quest;
alter table quest_item add constraint fk_quest_item_id_item foreign key (id_item) references item;


